### ISSUE TITLE
publish website

### ISSUE THREAD

**Issue by aghili371** [OrchardSkills/OrchardSkills.OrchardCore.Headless#1]
thank you for this great project.
i have a question, to publish project I have to publish the angular project in domain and orchard care project in a subdomain or other domain?

**Comment by OrchardSkills** [comment]
There are no restrictions where you can publish your domains.  In the Orchard Core Web application, CORS is enabled. Both can be deployed on Azure or even Something like Google Firebase.

**Comment by OrchardSkills** [comment]
There are no restrictions where you can publish your domains. In the Orchard Core Web application, CORS is enabled. Both can be deployed on Azure or even Something like Google Firebase.
